---
title: "Trelliscope Links"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo=TRUE, message=FALSE, warning=FALSE}
library(tidyverse)
library(trelliscopejs)
library(gapminder)
```

## Example Data

We will use the gapminder data set of different countries life expectancy to demonstrate how you can create links within a trelliscope.

```{r}
dat <- gapminder::gapminder
head(dat)
```

## Countries Life Expectancy Trelliscope



```{r echo=TRUE, warning=FALSE}

point_plot <- function(dat){
  ggplot(dat) +
    geom_point(aes(x = year, y = lifeExp)) +
    theme_bw()
}  

dat_count <- dat %>% 
  nest(-c(country,continent))

dat_count <- dat_count %>% 
  mutate(dat_plot = map_plot(data, point_plot))

dat_count %>% 
  trelliscope(name="Life Expectancy by Country",
              path = "~lifeExpectancy",
              thumb = T,
              nrow = 1, 
              ncol = 2
  )
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
